version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: jobapp-mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=job-applications
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Backend API Service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: jobapp-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/job-applications
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret_do_not_use_in_production}
      - SESSION_SECRET=${SESSION_SECRET:-default_session_secret_do_not_use_in_production}
      - LOG_LEVEL=info
    volumes:
      - ./Backend:/app
      - /app/node_modules
      - backend_logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "wget --quiet --spider http://localhost:3000/api/v1 || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  # Frontend Web Application
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: jobapp-frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:3000/api/v1
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongodb_data:
    name: jobapp-mongodb-data
  backend_logs:
    name: jobapp-backend-logs

networks:
  app-network:
    driver: bridge
    name: jobapp-network
