version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=job-applications
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: job-app-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/job-applications
      - JWT_SECRET=your_secure_jwt_secret_for_development
      - SESSION_SECRET=your_secure_session_secret_for_development
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongodb
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: job-app-frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - API_BASE_URL=http://backend:3000/api/v1
      - MODE=development
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge